name: Deploy to GitHub Pages (Main)

on:
  push:
    branches: ["main"]

# Mudamos as permissões para "write" para que o bot possa criar a nova branch
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # SE você usar algum comando para gerar a pasta /public (como npm run build), 
      # adicione os passos de Node.js e build aqui. 
      # Se a pasta /public já fica direto no seu repositório, pode ignorar este aviso.

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
